In [ ]:
import numpy as np
from cellpose import io, metrics, models, utils
import time
from tqdm import trange
from pathlib import Path
from natsort import natsorted
import tifffile
import benchmarks
import importlib
importlib.reload(benchmarks)


<module 'benchmarks' from '/media/carsen/ssd1/grive/transformers/benchmarks.py'>

### microsam, pathosam and cellposesam installation

env with microsam, pathosam and cellposesam installed:

```
conda create --name microsam python=3.12
conda activate microsam
conda install -c conda-forge microsam=1.4
pip install slideio
pip install git+https://github.com/computational-cell-analytics/patho-sam.git
pip install git+https://github.com/mouseland/cellpose.git
```

In [ ]:
io.logger_setup()

benchmarks.run_cellposesam()

benchmarks.run_microsam()

benchmarks.run_pathosam()

cyto2


100%|██████████| 67/67 [00:11<00:00,  5.94it/s]


[0.508344   0.2408148  0.02892172]
[0.67191124 1.2475212  1.8402342 ]


### cellsam, cellpose, samcell and omnipose installation

separate env with cellsam and cellpose==3.1.2 installed:

```
conda create --name cellsam python=3.11
conda activate cellsam
git clone https://github.com/vanvalenlab/cellSAM.git
cd cellSAM
# checkout latest working model (new commits download new model which performs poorly)
git checkout a392cdd199eebd11646cf6dd115a992af33f6365
pip install -e .
pip install cellpose==3.1.2
pip install segmentation_models_pytorch==0.4.0 # for segformer
```

to install samcell
```
git clone https://github.com/NathanMalta/SAMCell.git
cd SAMCell
pip install -r requirements.txt
```

and download models: https://github.com/NathanMalta/SAMCell/releases/tag/v1

to install omnipose:
```
git clone https://github.com/kevinjohncutler/omnipose.git
cd omnipose
pip install -e .
```

(**with newer torch versions need to edit omnipose/src/core.py torch.amp => torch.cuda.amp)

In [ ]:
importlib.reload(benchmarks)
io.logger_setup()
benchmarks.run_cyto3_segformer()

benchmarks.run_cellsam()

# path to github repo for SAMCell
import sys
sys.path.insert(0, "/github/SAMCell/src/")
benchmarks.run_samcell()

benchmarks.run_omnipose()


2025-04-19 16:50:49,355 [INFO] WRITING LOG OUTPUT TO /home/carsen/.cellpose/run.log
2025-04-19 16:50:49,357 [INFO] 
cellpose version: 	3.1.1.2.dev23+g9854949 
platform:       	linux 
python version: 	3.11.12 
torch version:  	2.0.0+cu117
['cyto2', 'bact_phase']
cyto2
2025-04-19 16:50:49,570 [INFO] ** TORCH CUDA version installed and working. **
2025-04-19 16:50:49,571 [INFO] >>>> using GPU (CUDA)
2025-04-19 16:50:49,572 [INFO] >> cyto3 << model set to be used
2025-04-19 16:50:49,632 [INFO] >>>> loading model /home/carsen/.cellpose/models/cyto3
2025-04-19 16:50:49,690 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)


/home/carsen/miniforge3/envs/cp_sam/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
 18%|█▊        | 12/67 [00:04<00:18,  3.03it/s]/media/carsen/ssd1/github/cellpose_main/cellpose/cellpose/transforms.py:602: UserWarning: 'chan2 (opt)' has value range of ZERO, can instead set chan2 to 0
  warnings.warn(
100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


[0.76919436 0.52135503 0.11868314]
[0.2966065 0.686529  1.5863004]
2025-04-19 16:51:21,128 [INFO] >> transformer_cp3 << model set to be used
2025-04-19 16:51:21,129 [INFO] ** TORCH CUDA version installed and working. **
2025-04-19 16:51:21,130 [INFO] >>>> using GPU (CUDA)


/home/carsen/miniforge3/envs/cp_sam/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2025-04-19 16:51:23,575 [INFO] >>>> loading model /home/carsen/.cellpose/models/transformer_cp3


/home/carsen/miniforge3/envs/cp_sam/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


2025-04-19 16:51:23,876 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)


  0%|          | 0/67 [00:00<?, ?it/s]/media/carsen/ssd1/github/cellpose_main/cellpose/cellpose/core.py:275: RuntimeWarning: invalid value encountered in divide
  stylei /= (stylei**2).sum()**0.5
100%|██████████| 67/67 [00:14<00:00,  4.60it/s]


[0.7772797  0.5244205  0.11813007]
[0.27432945 0.66893476 1.5724243 ]
bact_phase
2025-04-19 16:51:39,189 [INFO] ** TORCH CUDA version installed and working. **
2025-04-19 16:51:39,190 [INFO] >>>> using GPU (CUDA)
2025-04-19 16:51:39,192 [INFO] >> cyto3 << model set to be used
2025-04-19 16:51:39,256 [INFO] >>>> loading model /home/carsen/.cellpose/models/cyto3
2025-04-19 16:51:39,314 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)


/home/carsen/miniforge3/envs/cp_sam/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
  0%|          | 0/148 [00:00<?, ?it/s]/media/carsen/ssd1/github/cellpose_main/cellpose/cellpose/transforms.py:602: UserWarning: 'chan2 (opt)' has value range of ZERO, can instead set chan2 to 0
  warnings.warn(
100%|██████████| 148/148 [02:10<00:00,  1.13it/s]


[0.84341854 0.7950556  0.5272192 ]
[0.17854145 0.24416496 0.69877285]
2025-04-19 16:53:51,532 [INFO] >> transformer_cp3 << model set to be used
2025-04-19 16:53:51,534 [INFO] ** TORCH CUDA version installed and working. **
2025-04-19 16:53:51,536 [INFO] >>>> using GPU (CUDA)
2025-04-19 16:53:53,787 [INFO] >>>> loading model /home/carsen/.cellpose/models/transformer_cp3
2025-04-19 16:53:54,045 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)


100%|██████████| 148/148 [01:07<00:00,  2.20it/s]


[0.8308473  0.77529097 0.50729567]
[0.19531594 0.2719224  0.7323412 ]
